"""Report generation helpers for stock analysis results.

The UI layer moved to React, so this module only produces report content. HTTP
routes can return the generated bytes or text without importing Streamlit.
"""

from __future__ import annotations

import base64
import html
import io
from datetime import datetime
from typing import Any, Dict

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


AGENT_NAMES = {
    "technical": "技术分析师",
    "technical_analyst": "技术分析师",
    "fundamental": "基本面分析师",
    "fundamental_analyst": "基本面分析师",
    "fund_flow": "资金面分析师",
    "fund_analyst": "资金面分析师",
    "risk": "风险管理师",
    "risk_management": "风险管理师",
    "risk_analyst": "风险管理师",
    "sentiment": "市场情绪分析师",
    "market_sentiment": "市场情绪分析师",
    "sentiment_analyst": "市场情绪分析师",
    "news": "新闻分析师",
}


def _text(value: Any, default: str = "N/A") -> str:
    if value is None or value == "":
        return default
    if isinstance(value, dict):
        return value.get("analysis") or value.get("decision_text") or str(value)
    return str(value)


def generate_markdown_report(
    stock_info: Dict[str, Any],
    agents_results: Dict[str, Any],
    discussion_result: Any,
    final_decision: Any,
) -> str:
    """Generate a Markdown report for a stock-analysis result."""

    stock_info = stock_info or {}
    agents_results = agents_results or {}
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        "# AI股票分析报告",
        "",
        f"**生成时间**: {current_time}",
        "",
        "## 股票基本信息",
        "",
        "| 项目 | 值 |",
        "| --- | --- |",
        f"| 股票代码 | {_text(stock_info.get('symbol'))} |",
        f"| 股票名称 | {_text(stock_info.get('name'))} |",
        f"| 当前价格 | {_text(stock_info.get('current_price'))} |",
        f"| 涨跌幅 | {_text(stock_info.get('change_percent'))} |",
        f"| 市盈率 PE | {_text(stock_info.get('pe_ratio'))} |",
        f"| 市净率 PB | {_text(stock_info.get('pb_ratio'))} |",
        f"| 市值 | {_text(stock_info.get('market_cap'))} |",
        "",
        "## 分析师报告",
        "",
    ]

    for key, value in agents_results.items():
        agent_name = AGENT_NAMES.get(key, key)
        lines.extend([f"### {agent_name}", "", _text(value, "暂无分析"), ""])

    lines.extend(
        [
            "## 团队综合讨论",
            "",
            _text(discussion_result, "暂无讨论结果"),
            "",
            "## 最终投资决策",
            "",
        ]
    )

    if isinstance(final_decision, dict) and "decision_text" not in final_decision:
        for key, label in [
            ("rating", "投资评级"),
            ("target_price", "目标价位"),
            ("operation_advice", "操作建议"),
            ("entry_range", "进场区间"),
            ("take_profit", "止盈位"),
            ("stop_loss", "止损位"),
            ("holding_period", "持有周期"),
            ("position_size", "仓位建议"),
            ("confidence_level", "信心等级"),
            ("risk_warning", "风险提示"),
        ]:
            lines.append(f"**{label}**: {_text(final_decision.get(key), '暂无')}")
            lines.append("")
    else:
        lines.append(_text(final_decision, "暂无最终决策"))
        lines.append("")

    lines.extend(
        [
            "---",
            "",
            "本报告由AI系统生成，仅供研究参考，不构成投资建议。投资有风险，入市需谨慎。",
        ]
    )
    return "\n".join(lines)


def generate_html_content(markdown_content: str) -> str:
    """Render a lightweight HTML document from Markdown-like text."""

    body = html.escape(markdown_content)
    body = body.replace("\n", "<br />\n")
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <title>AI股票分析报告</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; line-height: 1.65; max-width: 960px; margin: 0 auto; padding: 32px; color: #111827; }}
    pre, code {{ white-space: pre-wrap; }}
  </style>
</head>
<body>{body}</body>
</html>"""


def create_pdf_report(
    stock_info: Dict[str, Any],
    agents_results: Dict[str, Any],
    discussion_result: Any,
    final_decision: Any,
) -> bytes:
    """Generate a compact PDF report."""

    markdown = generate_markdown_report(stock_info, agents_results, discussion_result, final_decision)
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=48, leftMargin=48, topMargin=48, bottomMargin=36)
    styles = getSampleStyleSheet()
    normal = ParagraphStyle("ReportNormal", parent=styles["Normal"], fontSize=10, leading=15, alignment=TA_LEFT)
    heading = ParagraphStyle("ReportHeading", parent=styles["Heading2"], fontSize=14, leading=18, spaceBefore=10)

    story = []
    for line in markdown.splitlines():
        if line.startswith("# "):
            story.append(Paragraph(html.escape(line[2:]), styles["Title"]))
        elif line.startswith("## "):
            story.append(Paragraph(html.escape(line[3:]), heading))
        elif line.startswith("| "):
            cells = [html.escape(part.strip()) for part in line.strip("|").split("|")]
            if len(cells) == 2 and cells != ["---", "---"]:
                table = Table([cells], colWidths=[120, 340])
                table.setStyle(
                    TableStyle(
                        [
                            ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                            ("VALIGN", (0, 0), (-1, -1), "TOP"),
                            ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke),
                        ]
                    )
                )
                story.append(table)
        elif line.strip():
            story.append(Paragraph(html.escape(line), normal))
        else:
            story.append(Spacer(1, 6))

    doc.build(story)
    return buffer.getvalue()


def create_download_link(content: bytes, filename: str) -> str:
    """Return a data URL link for callers that still need an inline download URL."""

    b64 = base64.b64encode(content).decode("ascii")
    return f'<a href="data:application/pdf;base64,{b64}" download="{html.escape(filename)}">下载PDF报告</a>'


def create_markdown_download_link(markdown_content: str, filename: str) -> str:
    b64 = base64.b64encode(markdown_content.encode("utf-8")).decode("ascii")
    return f'<a href="data:text/markdown;base64,{b64}" download="{html.escape(filename)}">下载Markdown报告</a>'


def display_pdf_export_section(*_args: Any, **_kwargs: Any) -> None:
    """Compatibility placeholder for the removed Streamlit UI."""

    raise RuntimeError("Streamlit UI has been removed. Use FastAPI report endpoints or React actions instead.")
